### ISSUE TITLE
Mystical Agriculture crashes my minecraft

### ISSUE THREAD

**Issue by AlcatrazIsle** [BlakeBr0/MysticalAgriculture#491]
**Describe the bug**
It crashes my Minecraft when it gets to it in the initializing mods tab. I've tried to redownload it or try other versions but nothing works. I am trying to download the 1.12.2, which is what I need. I have forge, java (oracale), cucumber, and it doesn't work. I've tried restarting too. This is what it tells me.

**To Reproduce**
I just download the mod and it doesn't let me open Minecraft properly. 

**Expected behavior**
I don't know what is happening, especially since I've been trying all night and now all day to get it working. 

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Agriculture (mysticalagriculture)
Exit Code: -1

Crash Log: 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
Contact their authors BEFORE contacting forge

Time: 2/10/22 4:00 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Agriculture (mysticalagriculture)
Caused by: java.lang.NoClassDefFoundError: com/blakebr0/mysticalagriculture/blocks/ModBlocks
	at com.blakebr0.mysticalagriculture.proxy.CommonProxy.preInit(CommonProxy.java:52)
	at com.blakebr0.mysticalagriculture.proxy.ClientProxy.preInit(ClientProxy.java:13)
	at com.blakebr0.mysticalagriculture.MysticalAgriculture.preInit(MysticalAgriculture.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.blakebr0.mysticalagriculture.blocks.ModBlocks
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.findAndMergeSuperMaps(FMLDeobfuscatingRemapper.java:425)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.mergeSuperMaps(FMLDeobfuscatingRemapper.java:455)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.findAndMergeSuperMaps(FMLDeobfuscatingRemapper.java:429)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldMap(FMLDeobfuscatingRemapper.java:384)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.mapFieldName(FMLDeobfuscatingRemapper.java:299)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.mapFieldName(FMLDeobfuscatingRemapper.java:290)
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLRemappingAdapter$StaticFixingMethodVisitor.visitFieldInsn(FMLRemappingAdapter.java:91)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:1494)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1032)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:708)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:521)
	at net.minecraftforge.fml.common.asm.transformers.DeobfuscationTransformer.transform(DeobfuscationTransformer.java:76)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 45 more

**Versions (please complete the following information):**
 - Minecraft: java version 1.12.2
 - Forge: 1.12.2-14.23.5.2860
 - Cucumber: 1.12.2-1.1.2
 - Mystical Agriculture: 1.12.2-1.7.5

**Comment by BlakeBr0** [comment]
Not sure what could cause this. Did you install the mod using the curseforge app? Could also be something like having a bad java version installed or a corrupted forge install.

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
