### ISSUE TITLE
[minecraft/RecipeManager]: Parsing error loading recipe mysticalagriculture:essence/chisel/marble

### ISSUE THREAD

**Issue by xXjojojXx** [BlakeBr0/MysticalAgriculture#581]
MysticalAgriculture-1.16.5-4.2.6.jar

when my server starts I get the following error message in the console is there a way to fix this error?

[18:06:10] [Worker-Main-8/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe mysticalagriculture:essence/chisel/marble
com.google.gson.JsonSyntaxException: Unknown item 'chisel:marble/raw'
	at net.minecraft.item.crafting.ShapedRecipe.func_222129_c(ShapedRecipe.java:262) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.util.Optional.orElseThrow(Optional.java:408) ~[?:?] {}
	at net.minecraft.item.crafting.ShapedRecipe.func_199798_a(ShapedRecipe.java:261) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at com.blakebr0.cucumber.crafting.recipe.ShapedNoMirrorRecipe$Serializer.fromJson(ShapedNoMirrorRecipe.java:71) ~[cucumber:4.1.12] {re:classloading}
	at com.blakebr0.cucumber.crafting.recipe.ShapedNoMirrorRecipe$Serializer.func_199425_a_(ShapedNoMirrorRecipe.java:62) ~[cucumber:4.1.12] {re:classloading}
	at net.minecraft.item.crafting.RecipeManager.func_215377_a(RecipeManager.java:141) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:61) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.item.crafting.RecipeManager.func_212853_a_(RecipeManager.java:38) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13) ~[?:?] {re:classloading,re:mixin}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?] {}
	at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53) ~[?:?] {re:classloading}
	at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) [?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1705) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?] {}

**Comment by BlakeBr0** [comment]
Do you have chisel installed?

**Comment by xXjojojXx** [comment]
no

**Comment by BlakeBr0** [comment]
Then this is normal. If you don't want to see the warning you would have to create a datapack and override the recipes to add conditions to disable them.
